version: 2

models:

  - name: monthly_revenue
    description: >
      Monthly recognized revenue aggregated from finished orders.
      Uses the revenue_recognition_date_utc field from fct_orders to group revenue by month.
      This metric helps track financial performance over time on a monthly basis.
    columns:
      - name: revenue_recognition_month_utc
        description: "The month (formatted as YYYY-MM) in which revenue from finished orders was recognized (in UTC)."
        tests:
          - not_null
      - name: revenue_eur
        description: "The total recognized revenue (in EUR) from finished orders in the given month."
        tests:
          - not_null

  - name: quarterly_revenue
    description: >
      Quarterly recognized revenue aggregated from finished orders.
      Uses the revenue_recognition_date_utc field from fct_orders to group revenue by quarter.
      Helps track longer-term revenue trends.
    columns:
      - name: revenue_recognition_quarter_utc
        description: "The quarter (formatted as Qn YYYY) in which revenue from finished orders was recognized."
        tests:
          - not_null
      - name: revenue_eur
        description: "The total recognized revenue (in EUR) from finished orders in the given quarter."
        tests:
          - not_null

  - name: yearly_revenue
    description: >
      Yearly recognized revenue aggregated from finished orders.
      Useful for high-level trend analysis and comparing annual business growth.
    columns:
      - name: revenue_recognition_year_utc
        description: "The year in which revenue from finished orders was recognized."
        tests:
          - not_null
      - name: revenue_eur
        description: "The total recognized revenue (in EUR) from finished orders in the given year."
        tests:
          - not_null

  - name: revenue_by_customer_group
    description: >
      Total recognized revenue (EUR) grouped by customer group type.
      Helps evaluate which customer segments contribute most to finished order revenue.
    columns:
      - name: customer_group_type
        description: "The type of customer group (e.g. company, private group, individual)."
        tests:
          - not_null
      - name: revenue_eur
        description: "Total revenue (in EUR) generated by customers in the given group from finished orders."
        tests:
          - not_null

  - name: revenue_by_route
    description: >
      Total recognized revenue (EUR) grouped by route.
      Useful for understanding route-level profitability and identifying high-revenue travel paths.
    columns:
      - name: route
        description: "The route (origin and destination pair) for the trip."
        tests:
          - not_null
      - name: revenue_eur
        description: "Total revenue (in EUR) generated on the given route from finished orders."
        tests:
          - not_null

  - name: revenue_per_seat
    description: >
      Revenue per available seat per trip.
      Normalizes revenue by airplane size to help evaluate efficiency and pricing performance across different trips and airplanes.
      (This assumes that Bolt has a say in determining seat price rather than just being a middle-man/platform provider for airlines, for example).
    columns:
      - name: trip_id
        description: "Unique identifier for the trip."
        tests:
          - not_null
          - relationships:
              to: ref('dim_orders')
              field: trip_id
      - name: airplane_id
        description: "Foreign key to dim_airplanes table."
        tests:
          - not_null
          - relationships:
              to: ref('dim_airplanes')
              field: airplane_id
      - name: max_seats
        description: "Total number of seats available on the airplane used for the trip."
        tests:
          - not_null
      - name: revenue_per_seat_eur
        description: "Revenue per available seat (EUR) for the given trip, calculated as total trip revenue divided by max_seats."
        tests:
          - not_null








